backend:
  name: github
  repo: melpers/nrl-gatsby
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  branch: v0.7
  use_graphql: true
  preview_context: federalist/build

media_folder: src/images/media
public_folder: /images/media
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - name: dresearch-division-landing-pages
    label: Research Division Landing Pages
    label_singular: Research Division Landing Page
    folder: src/pages/research-divisions/research-division-landing-pages
    create: true
    preview_path: 'areas-of-research/{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: "URL Path", name: "path", widget: "string" }
      - { label: 'Code', name: 'code', widget: 'string' }
      - { label: "Hero Image", name: "hero_image", widget: "hidden", default: "../../../images/header_faceted.jpg" }
      - { label: "Hero Size", name: "hero_size", widget: "hidden", default: "small" }
      - { label: "News Image", name: "news_image", widget: "hidden", default: "../../../images/8250-news.jpg" }
      - { label: "Publications Image", name: "publications_image", widget: "hidden", default: "../../../images/8250-pubs.jpg" }
      - { label: "Research Image", name: "research_image", widget: "hidden", default: "../../../images/8250-research.jpg" }
      - { label: "Videos Image", name: "videos_image", widget: "hidden", default: "../../../images/8250-videos.jpg" }
      - { label: "Template", name: "template", widget: "hidden", default: "division-landing" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
